docker:
  image: yegor256/rultor-image:1.3
architect:
  - baudoliver7
assets:
  settings.xml: "baudoliver7/home#assets/minlessika/settings.xml"
  pubring.kbx: "baudoliver7/home#assets/pubring.kbx"
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean    
    pdd --source=$(pwd) --verbose --file=/dev/null
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    pdd -f /dev/null
    mvn versions:set "-DnewVersion=${tag}" --settings ../settings.xml
    git commit -am "${tag}"
    mvn clean deploy -Pminlessika,publish,sonatype,qulice,gpg-sign --errors --settings ../settings.xml
