architect:
- baudoliver7
install:
- sudo gpgconf --kill dirmngr
- sudo chown -R $USER ~/.gnupg
assets:
  settings.xml: "baudoliver7/home#assets/minlessika/settings.xml"
  pubring.kbx: "baudoliver7/home#assets/pubring.kbx"
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean
  commanders:
  - baudoliver7
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -e
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Pminlessika --errors --settings ../settings.xml
    mvn clean site-deploy -Psite -Pminlessika --errors --settings ../settings.xml
  commanders:
  - baudoliver7
