name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15, windows-2019]
        java: [8, 11, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Test
        run: mvn clean test --errors --batch-mode
      - name: CodeCov
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-18.04' && matrix.java == 8 && github.repository == 'Minlessika/ppom'
        with:
          file: target/coverage/jacoco.xml

  lint:
    name: Linters
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install pdd, xcop
        run: |
          gem install pdd
          gem install xcop
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Puzzles
        run: pdd --file=/dev/null
      - name: Qulice
        run: mvn -P qulice clean install -DskipTests=true --errors --batch-mode
